//
// --------------------------------------------------------------------------
// ScrollSyntheticEvent.h
// Marks wheel events generated by Mac Mouse Fix itself.
// --------------------------------------------------------------------------
//

#ifndef ScrollSyntheticEvent_h
#define ScrollSyntheticEvent_h

#include <CoreGraphics/CoreGraphics.h>
#include <stdbool.h>
#include <stdint.h>

/// ASCII "MFSCROLL". A full 64-bit marker avoids confusing another process's
/// ordinary source-user-data value with our own output.
static const int64_t kMFScrollSyntheticEventUserData = 0x4D465343524F4C4C;

static inline void MFScrollMarkSyntheticEvent(CGEventRef event) {
    CGEventSetIntegerValueField(
        event,
        kCGEventSourceUserData,
        kMFScrollSyntheticEventUserData);
}

static inline bool MFScrollEventIsSynthetic(CGEventRef event) {
    return CGEventGetIntegerValueField(event, kCGEventSourceUserData)
        == kMFScrollSyntheticEventUserData;
}

#endif /* ScrollSyntheticEvent_h */
